MunSteam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('my/admin/', admin.site.urls),
    path('statistic/', include('statistic_from_user.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('achievements/', include('achievements.urls')),
    path('', include('games.urls')),
    path('friends/', include('friends.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + debug_toolbar_urls()

games/urls.py
from django.urls import path

from .views import MainView, GameView

app_name = 'games'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('game/<int:app_id>', GameView.as_view(), name='game')
]

statistic_from_user/urls.py
from django.urls import path
from rest_framework import routers

from . import views

urlpatterns = [
    path('', views.ChoiseView.as_view(), name='statistic'),
    path('ur/', views.YourStatisticView.as_view(), name='statistic_ur'),
    path('with_friends/', views.StatisticWithFriendsView.as_view(), name='statistic_with_friend'),
]

router = routers.DefaultRouter()
router.register(r'api/user_statistic', views.StatisticView)
urlpatterns += router.urls

user/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from rest_framework import routers

from . import views, api

app_name = 'user'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done',
         PasswordChangeDoneView.as_view(template_name='registration_temp/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(
            template_name='registration_temp/password_reset_form.html',
            email_template_name='registration_temp/password_reset_email.html',
            success_url=reverse_lazy("user:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done',
         PasswordResetDoneView.as_view(template_name='registration_temp/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='registration_temp/password_reset_confrim.html',
             success_url=reverse_lazy('user:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('password-reset/complete',
         PasswordResetCompleteView.as_view(template_name='registration_temp/password_reset_complete.html'),
         name='password_reset_complete'),
    path('detach-steam/', views.DetachSteamView.as_view(), name='detach_steam'),
    path('update-time/', views.UpdateView.as_view(), name='update_data')
]

router = routers.DefaultRouter()
router.register(r'api/recentlygame', api.RecentlyGameView)
router.register(r'api/telegram', api.UserTelegramView)
router.register(r'api/steam_info', api.UserInfoView)
urlpatterns += router.urls

statistic_from_user/models.py
from django.db import models

from user.models import SteamUser


class GameStats(models.Model):
    user_steam_id = models.CharField(max_length=50, unique=True, null=True)
    game_id = models.IntegerField(default=730)
    total_kills = models.IntegerField(null=True)
    total_deaths = models.IntegerField(null=True)
    total_time_played = models.IntegerField(null=True)
    total_planted_bombs = models.IntegerField(null=True)
    total_defused_bombs = models.IntegerField(null=True)
    total_damage_done = models.IntegerField(null=True)
    total_money_earned = models.IntegerField(null=True)
    total_wins_pistolround = models.IntegerField(null=True)
    total_mvps = models.IntegerField(null=True)
    total_matches_won = models.IntegerField(null=True)
    total_matches_played = models.IntegerField(null=True)

    def __str__(self):
        return str(self.user_steam_id)

    def money_earned(self):
        return str(self.total_money_earned) + '$'

    def time_played_hours(self):
        return (str(self.total_time_played // 3600) + ' часов '
                + str(self.total_time_played // 60 % 60) + ' минут')

statistic_from_user/views.py
from django.views import View
from django.shortcuts import render
from rest_framework.viewsets import ReadOnlyModelViewSet
from django_filters.rest_framework import DjangoFilterBackend

from friends.service import get_friends, get_info_friends
from .service import ur_statistic, get_stats_in_game
from .models import GameStats
from .serializer import StatsSerializer
from friends.models import UserFriends
from user.utils import SteamURLRequiredMixin


class YourStatisticView(SteamURLRequiredMixin, View):
    template_name = 'statistic_from_user.html'

    def get(self, request):
        user = request.user
        statistic = ur_statistic(user.steam_id)
        return render(request, self.template_name, context={
            'statistic': statistic,
        })

    def post(self, request):
        pass


class ChoiseView(SteamURLRequiredMixin, View):
    template_name = 'choice.html'

    def get(self, request):
        return render(request, self.template_name)

    def post(self, request):
        pass


class StatisticWithFriendsView(SteamURLRequiredMixin, View):
    template_name = 'statistic_with_friend.html'

    def get(self, request):
        user = request.user
        statistic = ur_statistic(user.steam_id)
        friends, text = get_info_friends(user.steam_id)
        statistic_friend = []
        if request.GET.get('friend'):
            get_stats_in_game(request.GET.get('friend'))
            statistic_friend = ur_statistic(request.GET.get('friend'))
        return render(request, self.template_name, context={
            'stat': statistic,
            'friends': friends,
            'stat_friend': statistic_friend,
            'text': text,
        })

    def post(self, request):
        pass


class StatisticView(ReadOnlyModelViewSet):
    queryset = GameStats.objects.all()
    serializer_class = StatsSerializer
    filter_backends = [DjangoFilterBackend]
    filterset_fields = ['user_steam_id', ]

    def get_queryset(self):
        return self.queryset.exclude(
            total_kills__isnull=True,
            total_deaths__isnull=True,
            total_time_played__isnull=True,
            total_planted_bombs__isnull=True,
            total_defused_bombs__isnull=True,
            total_damage_done__isnull=True,
            total_money_earned__isnull=True,
            total_wins_pistolround__isnull=True,
            total_mvps__isnull=True,
            total_matches_won__isnull=True,
            total_matches_played__isnull=True
        )

statistic_from_user/templates/choice.html
{% extends 'template_base.html' %}
{% load static %}
{% block head %}
<link href="{% static 'css/statistic.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}
Статистика
{% endblock %}

{% block content %}
<div class="container text-center" style="margin-top: 50px;">
    <div class="row justify-content-center">
        <div class="col-md-6">
            <a href="{% url 'statistic_ur' %}" class="btn btn-primary btn-lg btn-block mb-3">Посмотреть вашу статистику</a>
        </div>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-6">
            <a href="{% url 'statistic_with_friend' %}" class="btn btn-secondary btn-lg btn-block">Сравнить вашу статистику с другом</a>
        </div>
    </div>
</div>
{% endblock %}

statistic_from_user/templates/statistic_from_user.html
{% extends 'template_base.html' %}
{% load static %}
{% block head %}
<link href="{% static 'css/comparison.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}
Статистика по CS2
{% endblock %}

{% block content %}
<div class="container comparison-container">
    {% if statistic %}
    <div class="comparison-stats">
        <div class="player-profile">
            <img src="{{ user.avatarfull }}" alt="Ваш профиль" class="profile-image">
            <h4>{{ user.personaname }}</h4>
        </div>
        <div class="stats-comparison">
            <h4>Основные показатели</h4>
            <div class="stat">
                <span class="highlight">{{ statistic.total_kills }}</span>
                <span>Всего убийств</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.total_deaths }}</span>
                <span>Всего смертей</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.time_played_hours }}</span>
                <span>Общее время игры</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.total_planted_bombs }}</span>
                <span>Посажено бомб</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.total_defused_bombs }}</span>
                <span>Разминировано бомб</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.total_damage_done }}</span>
                <span>Урон</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.money_earned }}</span>
                <span>Денег заработано</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.total_wins_pistolround }}</span>
                <span>Победы в пистолетных раундах</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.total_mvps }}</span>
                <span>МВП</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.total_matches_won }}</span>
                <span>Победы в мм</span>
            </div>
            <div class="stat">
                <span class="highlight">{{ statistic.total_matches_played }}</span>
                <span>Матчей сыграно</span>
            </div>
        </div>
    </div>
    {% else %}
    <div class="alert alert-info" role="alert" style="margin-top: 30px;">
        <p>У вас нет CS2/Не удалось получить данные, возможно они скрыты</p>
        <a href="{% url 'games:main' %}" class="btn btn-primary">На главную</a>
        <a href="{% url 'user:profile' %}?reset_url=10321dsacsa2" class="btn btn-primary">Привязать другой аккаунт стим</a>
    </div>
    {% endif %}
</div>
{% endblock %}

statistic_from_user/templates/statistic_with_friend.html
{% extends 'template_base.html' %}
{% load static %}
{% block head %}
<link href="{% static 'css/comparison.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}
Сравнение статистики
{% endblock %}

{% block content %}
<div class="container comparison-container">
    {% if stat %}
    <form method="GET" class="comparison-form">
        <div class="form-group">
            <label for="friend">Выберите друга для сравнения статистики:</label>
            <select id="friend" name="friend" class="form-control">
                <option value="">--Выберите друга--</option>
                {% for friend in friends.friends_info %}
                    <option value="{{ friend.steamid }}" {% if friend.steamid == request.GET.friend %}selected{% endif %}>
                        {{ friend.personaname }}
                    </option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn btn-primary mt-2">Сравнить</button>
    </form>
    {% if request.GET.friend and stat_friend %}
    <div class="comparison-stats">
        <div class="player-profile">
            <img src="{{ user.avatarfull }}" alt="Ваш профиль" class="profile-image">
            <h4>{{ user.personaname }}</h4>
        </div>
        <div class="stats-comparison">
            <h4>Основные показатели</h4>
            <div class="stat">
                <span class="{% if stat.total_kills > stat_friend.total_kills %}highlight{% endif %}">{{ stat.total_kills }}</span>
                <span>Всего убийств</span>
                <span class="{% if stat_friend.total_kills > stat.total_kills %}highlight{% endif %}">{{ stat_friend.total_kills }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_deaths < stat_friend.total_deaths %}highlight{% endif %}">{{ stat.total_deaths }}</span>
                <span>Всего смертей</span>
                <span class="{% if stat_friend.total_deaths < stat.total_deaths %}highlight{% endif %}">{{ stat_friend.total_deaths }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_time_played > stat_friend.total_time_played %}highlight{% endif %}">{{ stat.time_played_hours }}</span>
                <span>Общее время игры</span>
                <span class="{% if stat_friend.total_time_played > stat.total_time_played %}highlight{% endif %}">{{ stat_friend.time_played_hours }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_planted_bombs > stat_friend.total_planted_bombs %}highlight{% endif %}">{{ stat.total_planted_bombs }}</span>
                <span>Посажено бомб</span>
                <span class="{% if stat_friend.total_planted_bombs > stat.total_planted_bombs %}highlight{% endif %}">{{ stat_friend.total_planted_bombs }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_defused_bombs > stat_friend.total_defused_bombs %}highlight{% endif %}">{{ stat.total_defused_bombs }}</span>
                <span>Разминировано бомб</span>
                <span class="{% if stat_friend.total_defused_bombs > stat.total_defused_bombs %}highlight{% endif %}">{{ stat_friend.total_defused_bombs }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_damage_done > stat_friend.total_damage_done %}highlight{% endif %}">{{ stat.total_damage_done }}</span>
                <span>Урон</span>
                <span class="{% if stat_friend.total_damage_done > stat.total_damage_done %}highlight{% endif %}">{{ stat_friend.total_damage_done }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_money_earned > stat_friend.total_money_earned %}highlight{% endif %}">{{ stat.money_earned }}</span>
                <span>Денег заработано</span>
                <span class="{% if stat_friend.total_money_earned > stat.total_money_earned %}highlight{% endif %}">{{ stat_friend.money_earned }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_wins_pistolround > stat_friend.total_wins_pistolround %}highlight{% endif %}">{{ stat.total_wins_pistolround }}</span>
                <span>Победы в пистолетных раундах</span>
                <span class="{% if stat_friend.total_wins_pistolround > stat.total_wins_pistolround %}highlight{% endif %}">{{ stat_friend.total_wins_pistolround }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_mvps > stat_friend.total_mvps %}highlight{% endif %}">{{ stat.total_mvps }}</span>
                <span>МВП</span>
                <span class="{% if stat_friend.total_mvps > stat.total_mvps %}highlight{% endif %}">{{ stat_friend.total_mvps }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_matches_won > stat_friend.total_matches_won %}highlight{% endif %}">{{ stat.total_matches_won }}</span>
                <span>Победы в мм</span>
                <span class="{% if stat_friend.total_matches_won > stat.total_matches_won %}highlight{% endif %}">{{ stat_friend.total_matches_won }}</span>
            </div>
            <div class="stat">
                <span class="{% if stat.total_matches_played > stat_friend.total_matches_played %}highlight{% endif %}">{{ stat.total_matches_played }}</span>
                <span>Матчей сыграно</span>
                <span class="{% if stat_friend.total_matches_played > stat.total_matches_played %}highlight{% endif %}">{{ stat_friend.total_matches_played }}</span>
            </div>
            <!-- Добавьте другие статистики аналогично -->
        </div>
        {% for friend in friends.friends_info %}
            {% if friend.steamid == request.GET.friend %}
                <div class="player-profile">
                    <img src="{{ friend.avatarfull }}" alt="Профиль друга" class="profile-image">
                    <h4>{{ friend.personaname }}</h4>
                </div>
            {% endif %}
        {% endfor %}
    </div>
    {% elif request.GET.friend and not stat_friend %}
        <div class="alert alert-info" role="alert" style="margin-top: 30px;">
            <p>У вашего друга нет статистики по CS2, либо у него закрытый аккаунт, выберите другого друга</p>
            <a href="{% url 'games:main' %}" class="btn btn-primary">На главную</a>
        </div>
    {% endif %}
    {% else %}
        <div class="alert alert-info" role="alert" style="margin-top: 30px;">
            <p>У вас нет CS2/Не удалось получить данные, возможно они скрыты</p>
            <a href="{% url 'games:main' %}" class="btn btn-primary">На главную</a>
            <a href="{% url 'user:profile' %}?reset_url=10321dsacsa2" class="btn btn-primary">Привязать другой аккаунт Steam</a>
        </div>
    {% endif %}
</div>
{% endblock %}

statistic_from_user/templates/template_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="icon" href="{% static 'img/img_site.png' %}" type="image/png">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz" crossorigin="anonymous"></script>
    <link rel="manifest" href="{% static 'favicon/site.webmanifest' %}">
    <link rel="mask-icon" href="{% static 'favicon/safari-pinned-tab.svg' %}" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/styles/default.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/highlight.min.js"></script>
    {% block head %} {% endblock %}
    <!-- and it's easy to individually load additional languages -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.8.0/languages/go.min.js"></script>

    <title>{% block title %}{% endblock %}</title>
    <!-- Google Tag Manager -->
    <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
    new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
    j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
    'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
    })(window,document,'script','dataLayer','GTM-KFVDXM9B');</script>
    <!-- End Google Tag Manager -->
</head>

<body style="min-height: 100vh; display: flex; flex-direction: column; justify-content: space-between">
    <!-- Google Tag Manager (noscript) -->
    <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KFVDXM9B"
    height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
    <!-- End Google Tag Manager (noscript) -->
    <!-- Yandex.Metrika counter -->
    <script type="text/javascript" >
       (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
       m[i].l=1*new Date();
       for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
       k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
       (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

       ym(95314788, "init", {
            clickmap:true,
            trackLinks:true,
            accurateTrackBounce:true
       });
    </script>
    <noscript><div><img src="https://mc.yandex.ru/watch/95314788" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
    <nav class="navbar navbar-expand-lg" style="background-color: #e3f2fd;">
      <div class="container">
          <div class="fs-2 me-2 nav-link"><a class="nav-link navbar-brand fs-4" href="/">🎮 MunSteam</a></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item active">
                <a class="nav-link" href="/">Игры</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/statistic">Ваша статистика по CS2</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/achievements">Достижения</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/friends/list">Друзья</a>
              </li>
          </ul>
          {% if user.is_authenticated %}
          <ul class="navbar-nav ms-auto d-flex align-items-center">
            <li class="nav-item">
                <a class="nav-link navbar-brand" href="/user/profile"><img src="{{ user.avatarfull }}" alt="useravatar" width="30" height="30"> {{ user.username }}</a>
            </li>
            <li class="nav-item">
                <a class="btn btn-sm btn-danger me-2" href="{% url 'user:logout' %}" type="button">Выйти</a>
            </li>
        </ul>

      {% else %}
          <ul class="navbar-nav ms-auto">
              <li class="nav-item"><a class="btn btn-sm btn-danger me-2" href="{% url 'user:login' %}" target="_blank" type="button">Войти</a></li>
            <li class="nav-item"><a class="btn btn-sm btn-danger" href="{% url 'user:register' %}" target="_blank" type="button">Зарегистрироваться</a></li>
        </ul>
      {% endif %}
          </div>
      </div>
      </div>
    </nav>
    <main class="container" style="flex: 1 1 auto;">
        {% block content %}
        {% endblock %}
    </main>
<script>hljs.highlightAll();</script>
</body>

<div class="container">
  <footer class="py-3 my-4">
    <p class="text-center nav-item nav-link px-2 text-body-secondary text-decoration-none text-reset fs-6">
      🎮 MunSteam by Данила Артёмович
    </p>
    <ul class="nav justify-content-center pb-1 mb-1">
      <li class="nav-item">
        <a href="https://t.me/n1lrin" target="_blank" class="nav-link px-2 text-body-secondary text-decoration-none text-reset fs-6">
          <i class="bi bi-telegram"></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="https://github.com/N1lrinside" target="_blank" class="nav-link px-2 text-body-secondary text-decoration-none text-reset fs-6">
          <i class="bi bi-github"></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="https://www.linkedin.com/in/danila-zorin-203770308/" target="_blank" class="nav-link px-2 text-body-secondary text-decoration-none text-reset fs-6">
          <i class="bi bi-linkedin"></i>
        </a>
      </li>
      <li class="nav-item">
        <a href="https://www.donationalerts.com/r/munsteam" target="_blank" class="nav-link px-2 text-body-secondary text-decoration-none text-reset fs-6">
          <!-- Donationalerts Icon -->
          <img src="{% static 'img/DonationAlerts Logo.png' %}" alt="Donationalerts" width="24" height="24">
        </a>
      </li>
    </ul>
    <div class="text-center">
      <a href="https://steamcommunity.com/" target="_blank">
        <img src="https://community.akamai.steamstatic.com/public/images/signinthroughsteam/sits_01.png" width="180" height="35" border="0" alt="Sign in through Steam">
      </a>
    </div>
  </footer>
</div>
</html>