MunSteam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('my/admin/', admin.site.urls),
    path('statistic/', include('statistic_from_user.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('achievements/', include('achievements.urls')),
    path('', include('games.urls')),
    path('friends/', include('friends.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + debug_toolbar_urls()

games/urls.py
from django.urls import path

from .views import MainView, GameView

app_name = 'games'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('game/<int:app_id>', GameView.as_view(), name='game')
]

user/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from rest_framework import routers

from . import views, api

app_name = 'user'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done',
         PasswordChangeDoneView.as_view(template_name='registration_temp/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(
            template_name='registration_temp/password_reset_form.html',
            email_template_name='registration_temp/password_reset_email.html',
            success_url=reverse_lazy("user:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done',
         PasswordResetDoneView.as_view(template_name='registration_temp/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='registration_temp/password_reset_confrim.html',
             success_url=reverse_lazy('user:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('password-reset/complete',
         PasswordResetCompleteView.as_view(template_name='registration_temp/password_reset_complete.html'),
         name='password_reset_complete'),
    path('detach-steam/', views.DetachSteamView.as_view(), name='detach_steam'),
    path('update-time/', views.UpdateView.as_view(), name='update_data')
]

router = routers.DefaultRouter()
router.register(r'api/recentlygame', api.RecentlyGameView)
router.register(r'api/telegram', api.UserTelegramView)
router.register(r'api/steam_info', api.UserInfoView)
urlpatterns += router.urls

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Sum


class SteamUser(AbstractUser):
    PERSONA_STATE_CHOICES = [
        (0, 'Оффлайн'),
        (1, 'Онлайн'),
        (2, 'Занят'),
        (3, 'Отсутствует'),
        (4, 'Отложен'),
        (5, 'Хочет обменять'),
        (6, 'Хочет поиграть'),
    ]

    PROFILE_STATE_CHOICES = [
        (1, 'Приватный'),
        (3, 'Общедоступный'),
    ]

    steam_id = models.CharField(max_length=20, null=True)
    personaname = models.CharField(max_length=255, null=True, blank=True, default='Нет информации')
    profileurl = models.URLField(null=True)
    avatarfull = models.URLField(null=True, blank=True, default='https://bootdey.com/img/Content/avatar/avatar7.png')
    personastate = models.IntegerField(choices=PERSONA_STATE_CHOICES, null=True, blank=True)
    profilestate = models.BooleanField(null=True, default=False)
    communityvisibilitystate = models.IntegerField(choices=PROFILE_STATE_CHOICES, null=True, blank=True)
    gameextrainfo = models.CharField(max_length=255, null=True, blank=True)
    createdacc_time = models.DateTimeField(null=True, blank=True)
    lastlogoff_time = models.DateTimeField(null=True, blank=True)
    last_update = models.DateField(null=True)
    last_update_url = models.DateTimeField(null=True)

    def check_auth(self):
        if self.profileurl is None:
            return False
        return True

    def check_status(self):
        if self.communityvisibilitystate == 1:
            return False
        return True


class UserRecentlyPlayedGames(models.Model):
    user_steam_id = models.CharField(max_length=50, null=True)
    app_id = models.CharField(max_length=10, null=True)
    name = models.CharField(max_length=50, null=True)
    playtime_2weeks = models.IntegerField(null=True)
    total_playtime_2weeks = models.IntegerField(null=True)
    percentage = models.FloatField(null=True)
    img_icon_url = models.URLField()

    def __str__(self):
        return self.user_steam_id + self.name

    def playtime_2weeks_hours(self):
        return round(self.playtime_2weeks / 60, 1)

    def total_playtime_2weeks_hours(self):
        return round(self.total_playtime_2weeks / 60, 1)

    class Meta:
        unique_together = ('user_steam_id', 'app_id')


class TelegramUser(models.Model):
    user = models.OneToOneField(SteamUser, on_delete=models.CASCADE)
    telegram_id = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.user.personaname

user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django import forms

from .service import get_id


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("На эту почту уже привязан аккаунт")
        return email


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class SteamUrlForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('profileurl', )
        widgets = {
            'profileurl': forms.TextInput(attrs={'style': 'width: 400px;'})
        }

    def clean_profileurl(self):
        url = self.cleaned_data.get('profileurl')
        try:
            steam_id = get_id(url)
            if steam_id is None:
                raise forms.ValidationError("Не удалось извлечь Steam ID из ссылки.")
            return url
        except AttributeError:
            raise forms.ValidationError("Неверная ссылка")


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль",
                                   widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

user/views.py
from datetime import date, datetime

from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View

from .forms import RegisterForm, LoginUserForm, SteamUrlForm, UserPasswordChangeForm
from .service import get_id, get_data_user, get_recently_games, detach_steam, connect_telegram, check_update_url, reset_update_url
from .tasks import update_info


class ProfileView(LoginRequiredMixin, View):
    template_name = 'pers_account.html'

    def get(self, request):
        user = request.user
        connect_telegram(request)
        reset_update_url(request, user)
        context = check_update_url(user)
        context['form'] = SteamUrlForm()
        return render(request, self.template_name, context=context)

    def post(self, request):
        form = SteamUrlForm(request.POST)
        user = request.user
        if form.is_valid():
            steam_id = get_id(form.cleaned_data.get('profileurl'))
            user.steam_id = steam_id
            user.profileurl = form.cleaned_data.get('profileurl')
            info_user = get_data_user(steam_id)
            user.personaname, user.avatarfull, user.personastate, user.profilestate = info_user[:4]
            user.communityvisibilitystate, user.gameextrainfo, user.createdacc_time, user.lastlogoff_time = info_user[4:]
            update_info.delay(steam_id)
            user.last_update_url = datetime.now()
            user.last_update = None
            get_recently_games(steam_id)
            user.save()
            return redirect('user:profile')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context=context)


class RegisterView(View):
    template_name = 'registration_temp/register.html'

    def get(self, request):
        context = {
            'form': RegisterForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('user:profile')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


class LoginUserView(LoginView):
    form_class = LoginUserForm
    template_name = 'registration_temp/login.html'
    extra_context = {'title': 'Авторизация'}


class UserPasswordChangeView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = "registration_temp/password_change_form.html"
    success_url = reverse_lazy("user:password_change_done")


class DetachSteamView(LoginRequiredMixin, View):

    def get(self, request):
        pass

    def post(self, request):
        user = request.user
        detach_steam(user)
        return redirect('user:profile')


class UpdateView(LoginRequiredMixin, View):

    def get(self, request):
        pass

    def post(self, request):
        user = request.user
        update_info.delay(user.steam_id)
        user.last_update = date.today()
        user.save()
        return redirect('user:profile')

user/templates/base_user.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link href="{% static 'css/login.css' %}" rel="stylesheet">
    <link href="{% static 'css/password_change_done.css' %}" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" rel="stylesheet">
    <link href="https://use.fontawesome.com/releases/v5.2.0/css/fontawesome.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
{% block content %}
{% endblock %}

user/templates/check_auth_user.html
{% extends 'template_base.html' %}
{% load static %}
{% block head %}
<link href="{% static 'css/statistic_user.css' %}" rel="stylesheet">
{% endblock %}
{% block title %}
Привяжите аккаунт стим
{% endblock %}

{% block content %}
<div class="container">
    <div class="alert alert-info" role="alert">
        <p>Пожалуйста, привяжите аккаунт стим, чтобы просмотреть информацию.</p>
        <a href="{% url 'user:profile' %}" class="btn btn-primary">Профиль</a>
    </div>
</div>
{% endblock %}

user/templates/check_status_user.html
{% extends 'template_base.html' %}
{% load static %}
{% block title %}У вас закрытый аккаунт{% endblock %}
{% block content %}
    <div class="alert alert-info" role="alert">
        <p>У вас закрытый профиль</p>
        <a href="{% url 'games:main' %}" class="btn btn-primary">На главную</a>
        <a href="{% url 'user:profile' %}" class="btn btn-primary">Привязать другой аккаунт стим</a>
    </div>
{% endblock %}

user/templates/pers_account.html
{% extends 'template_base.html' %}
{% load static %}
{% block head %}
    <meta charset="UTF-8">
    <link href="{% static 'css/pers_account.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet">
    <script type="text/javascript" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-alpha1/dist/js/bootstrap.bundle.min.js"></script>
    <script type="text/javascript" href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
{% endblock %}
<title>{% block title %}Профиль{% endblock %}</title>

{% block content %}
<div class="container">
    <div class="main-body">
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">
                    <img src="{{ user.avatarfull }}" alt="Admin" class="rounded-circle" width="150">
                    <div class="mt-3">
                      <h4>{{ user.username }}</h4>
                      <p class="text-secondary mb-1">Пользователь Стима</p>
                        {% if user.profilestate %}
                            <p class="text-muted font-size-sm">Профиль: {{ user.get_communityvisibilitystate_display }}</p>
                            <p class="text-muted font-size-sm">Статус: {{ user.get_personastate_display }}</p>
                        {% endif %}
                        {% load tz %}
                        {% if user.last_update == today %}
                            <p class="text-muted">Вы уже обновляли данные сегодня. Попробуйте завтра.</p>
                        {% else %}
                            <form method="post" action="{% url 'user:update_data' %}">
                                {% csrf_token %}
                                <button class="btn btn-outline-primary" type="submit">Обновить данные</button>
                            </form>
                        {% endif %}
                      <button class="btn btn-primary" onclick="location.href='/user/logout'">Выйти</button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Full Name</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.personaname }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.email }}
                    </div>
                  </div>
                  <hr>
                    <div class="row">
                      <div class="col-sm-3">
                        <h6 class="mb-0"><img src="{% static 'img/steam.png' %}" alt="Steam" width="24" height="24"> SteamUrl</h6>
                      </div>
                      <div class="col-sm-9 text-secondary" id="steamurlupdate">
                        {% if user.profileurl %}

                          <p>{{ user.profileurl }}</p>
                            <form method="post" action="{% url 'user:detach_steam' %}">
                                {% csrf_token %}
                                {% if not user.check_status %}
                                     <div class="alert alert-warning mt-4" role="alert">
                                        <strong>⚠ Ваш профиль закрыт.</strong> Доступ к множеству функций недоступен.
                                     </div>
                                    <button type="submit" class="btn btn-primary mt-2">Открепить</button>
                                {% elif can_detach %}
                                    <button type="submit" class="btn btn-primary mt-2">Открепить</button>
                                {% else %}
                                <p class="text-muted">Вы уже открепляли аккаунт менее 3 часов назад. Пожалуйста, попробуйте позже. Последнее прикрепление {{ user.last_update_url }}</p>
                                {% endif %}
                            </form>
                        {% else %}

                          <!-- Если у пользователя нет привязанного Steam URL, показываем форму -->
                          <form method="post">
                            {% csrf_token %}
                            <div class="form-group">
                                <div class="form-error">{{ form.non_field_errors }}</div>
                              <p><label class="form-label" for="{{ form.id_for_label }}">{{ form.label }}</label>{{ form.profileurl  }}</p>
		                        <div class="form-error">{{ form.profileurl.errors }}</div>
                            </div>
                            <button type="submit" class="btn btn-primary mt-2">Прикрепить</button>
                          </form>
                        {% endif %}
                      </div>
                    </div>
                    <hr>
                {% if not user.personastate %}
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Когда был последний раз в сети</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      {{ user.lastlogoff_time }}
                    </div>
                  </div>
                {% endif %}
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Когда был создан аккаунт</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                        {{ user.createdacc_time }}
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-12">
                      <a class="btn btn-info " target="__blank" href="{% url 'user:password_change' %}">Изменить Пароль</a>
                    </div>
                  </div>
                </div>
              </div>
            {% if games %}
  <div class="card mb-3">
    <div class="card-body">
      <h6 class="d-flex align-items-center mb-3">
        <i class="material-icons text-info mr-2">Последняя активность за две недели: {{ total_playtime.total_playtime_2weeks_hours }} часов</i>
      </h6>

      {% for game in games %}
      <div class="mb-2 d-flex justify-content-between align-items-center">
        <div class="d-flex align-items-center">
          <img src="{{ game.img_icon_url }}" alt="gameicon" width="30" height="30">
          <small class="ml-2">{{ game.name }}</small>
        </div>
        <small>{{ game.playtime_2weeks_hours }} часов</small>
      </div>
      <div class="progress mb-3" style="height: 5px">
        <div class="progress-bar bg-primary" role="progressbar" style="width: {{ game.percentage|floatformat:0 }}%" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100"></div>
      </div>
      {% endfor %}
    </div>
  </div>
{% endif %}
            </div>
          </div>
        </div>
    </div>
    <script>document.getElementById('detach-btn').addEventListener('click', function() {
        fetch('{% url "user:detach_steam" %}', {
            method: 'POST',
            headers: {
                'X-CSRFToken': '{{ csrf_token }}'
            }
        })
        .then(response => response.json())
        .then(data => {
            if (data.success) {
                // Очистить контент и показать форму привязки
                document.getElementById('steamurlupdate').innerHTML = `<form id="steam-url-form">{% csrf_token %}<div class="form-group"><div id="form-error" class="form-error"></div><p><label class="form-label" for="{{ form.id_for_label }}">{{ form.label }}</label>{{ form.profileurl }}</p><div id="field-error" class="form-error"></div></div><button type="submit" class="btn btn-primary mt-2">Прикрепить</button></form>`;
            }
        });
    });
</script>
{% endblock %}