MunSteam/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from debug_toolbar.toolbar import debug_toolbar_urls

urlpatterns = [
    path('my/admin/', admin.site.urls),
    path('statistic/', include('statistic_from_user.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('achievements/', include('achievements.urls')),
    path('', include('games.urls')),
    path('friends/', include('friends.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + debug_toolbar_urls()

games/urls.py
from django.urls import path

from .views import MainView, GameView

app_name = 'games'

urlpatterns = [
    path('', MainView.as_view(), name='main'),
    path('game/<int:app_id>', GameView.as_view(), name='game')
]

user/urls.py
from django.contrib.auth.views import LogoutView, PasswordChangeDoneView, PasswordResetView, PasswordResetDoneView, \
    PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, reverse_lazy
from rest_framework import routers

from . import views, api

app_name = 'user'

urlpatterns = [
    path('profile/', views.ProfileView.as_view(), name="profile"),
    path('register/', views.RegisterView.as_view(), name="register"),
    path('login/', views.LoginUserView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name="logout"),
    path('password-change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password-change/done',
         PasswordChangeDoneView.as_view(template_name='registration_temp/password_change_done.html'),
         name='password_change_done'),
    path('password-reset/',
         PasswordResetView.as_view(
            template_name='registration_temp/password_reset_form.html',
            email_template_name='registration_temp/password_reset_email.html',
            success_url=reverse_lazy("user:password_reset_done")
         ),
         name='password_reset'),
    path('password-reset/done',
         PasswordResetDoneView.as_view(template_name='registration_temp/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(
             template_name='registration_temp/password_reset_confrim.html',
             success_url=reverse_lazy('user:password_reset_complete')
         ),
         name='password_reset_confirm'),
    path('password-reset/complete',
         PasswordResetCompleteView.as_view(template_name='registration_temp/password_reset_complete.html'),
         name='password_reset_complete'),
    path('detach-steam/', views.DetachSteamView.as_view(), name='detach_steam'),
    path('update-time/', views.UpdateView.as_view(), name='update_data')
]

router = routers.DefaultRouter()
router.register(r'api/recentlygame', api.RecentlyGameView)
router.register(r'api/telegram', api.UserTelegramView)
router.register(r'api/steam_info', api.UserInfoView)
urlpatterns += router.urls

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models import Sum


class SteamUser(AbstractUser):
    PERSONA_STATE_CHOICES = [
        (0, 'Оффлайн'),
        (1, 'Онлайн'),
        (2, 'Занят'),
        (3, 'Отсутствует'),
        (4, 'Отложен'),
        (5, 'Хочет обменять'),
        (6, 'Хочет поиграть'),
    ]

    PROFILE_STATE_CHOICES = [
        (1, 'Приватный'),
        (3, 'Общедоступный'),
    ]

    steam_id = models.CharField(max_length=20, null=True)
    personaname = models.CharField(max_length=255, null=True, blank=True, default='Нет информации')
    profileurl = models.URLField(null=True)
    avatarfull = models.URLField(null=True, blank=True, default='https://bootdey.com/img/Content/avatar/avatar7.png')
    personastate = models.IntegerField(choices=PERSONA_STATE_CHOICES, null=True, blank=True)
    profilestate = models.BooleanField(null=True, default=False)
    communityvisibilitystate = models.IntegerField(choices=PROFILE_STATE_CHOICES, null=True, blank=True)
    gameextrainfo = models.CharField(max_length=255, null=True, blank=True)
    createdacc_time = models.DateTimeField(null=True, blank=True)
    lastlogoff_time = models.DateTimeField(null=True, blank=True)
    last_update = models.DateField(null=True)
    last_update_url = models.DateTimeField(null=True)

    def check_auth(self):
        if self.profileurl is None:
            return False
        return True

    def check_status(self):
        if self.communityvisibilitystate == 1:
            return False
        return True


class UserRecentlyPlayedGames(models.Model):
    user_steam_id = models.CharField(max_length=50, null=True)
    app_id = models.CharField(max_length=10, null=True)
    name = models.CharField(max_length=50, null=True)
    playtime_2weeks = models.IntegerField(null=True)
    total_playtime_2weeks = models.IntegerField(null=True)
    percentage = models.FloatField(null=True)
    img_icon_url = models.URLField()

    def __str__(self):
        return self.user_steam_id + self.name

    def playtime_2weeks_hours(self):
        return round(self.playtime_2weeks / 60, 1)

    def total_playtime_2weeks_hours(self):
        return round(self.total_playtime_2weeks / 60, 1)

    class Meta:
        unique_together = ('user_steam_id', 'app_id')


class TelegramUser(models.Model):
    user = models.OneToOneField(SteamUser, on_delete=models.CASCADE)
    telegram_id = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.user.personaname

user/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, PasswordChangeForm
from django import forms

from .service import get_id


class RegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data['email']
        if get_user_model().objects.filter(email=email).exists():
            raise forms.ValidationError("На эту почту уже привязан аккаунт")
        return email


class LoginUserForm(AuthenticationForm):
    username = forms.CharField(label='Логин',
                               widget=forms.TextInput(attrs={'class': 'form-input'}))
    password = forms.CharField(label='Пароль',
                               widget=forms.PasswordInput(attrs={'class': 'form-input'}))

    class Meta:
        model = get_user_model()
        fields = ('username', 'password')


class SteamUrlForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ('profileurl', )
        widgets = {
            'profileurl': forms.TextInput(attrs={'style': 'width: 400px;'})
        }

    def clean_profileurl(self):
        url = self.cleaned_data.get('profileurl')
        try:
            steam_id = get_id(url)
            if steam_id is None:
                raise forms.ValidationError("Не удалось извлечь Steam ID из ссылки.")
            return url
        except AttributeError:
            raise forms.ValidationError("Неверная ссылка")


class UserPasswordChangeForm(PasswordChangeForm):
    old_password = forms.CharField(label="Старый пароль",
                                   widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password1 = forms.CharField(label="Новый пароль",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))
    new_password2 = forms.CharField(label="Подтверждение пароля",
                                    widget=forms.PasswordInput(attrs={'class': 'form-input'}))

user/views.py
from datetime import date, datetime

from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView, PasswordChangeView
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View

from .forms import RegisterForm, LoginUserForm, SteamUrlForm, UserPasswordChangeForm
from .service import get_id, get_data_user, get_recently_games, detach_steam, connect_telegram, check_update_url, reset_update_url
from .tasks import update_info


class ProfileView(LoginRequiredMixin, View):
    template_name = 'pers_account.html'

    def get(self, request):
        user = request.user
        connect_telegram(request)
        reset_update_url(request, user)
        context = check_update_url(user)
        context['form'] = SteamUrlForm()
        return render(request, self.template_name, context=context)

    def post(self, request):
        form = SteamUrlForm(request.POST)
        user = request.user
        if form.is_valid():
            steam_id = get_id(form.cleaned_data.get('profileurl'))
            user.steam_id = steam_id
            user.profileurl = form.cleaned_data.get('profileurl')
            info_user = get_data_user(steam_id)
            user.personaname, user.avatarfull, user.personastate, user.profilestate = info_user[:4]
            user.communityvisibilitystate, user.gameextrainfo, user.createdacc_time, user.lastlogoff_time = info_user[4:]
            update_info.delay(steam_id)
            user.last_update_url = datetime.now()
            user.last_update = None
            get_recently_games(steam_id)
            user.save()
            return redirect('user:profile')
        context = {
            'form': form,
        }
        return render(request, self.template_name, context=context)


class RegisterView(View):
    template_name = 'registration_temp/register.html'

    def get(self, request):
        context = {
            'form': RegisterForm()
        }
        return render(request, self.template_name, context)

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=password)
            login(request, user)
            return redirect('user:profile')
        context = {
            'form': form
        }
        return render(request, self.template_name, context)


class LoginUserView(LoginView):
    form_class = LoginUserForm
    template_name = 'registration_temp/login.html'
    extra_context = {'title': 'Авторизация'}


class UserPasswordChangeView(PasswordChangeView):
    form_class = UserPasswordChangeForm
    template_name = "registration_temp/password_change_form.html"
    success_url = reverse_lazy("user:password_change_done")


class DetachSteamView(LoginRequiredMixin, View):

    def get(self, request):
        pass

    def post(self, request):
        user = request.user
        detach_steam(user)
        return redirect('user:profile')


class UpdateView(LoginRequiredMixin, View):

    def get(self, request):
        pass

    def post(self, request):
        user = request.user
        update_info.delay(user.steam_id)
        user.last_update = date.today()
        user.save()
        return redirect('user:profile')

user/templates/registration_temp/login.html
{% extends 'base_user.html' %}
{% block title %}
Логин
{% endblock %}
{% block content %}
<body>
    <div class="container">
        <div class="screen">
            <div class="screen__content">
                <form class="login" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}"/>
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <div class="login__field">
                        <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                        {{ f }}
                        <div class="row-form-errors">{{ f.errors }}</div>
                    </div>
                    {% endfor %}
                    <div class="login__actions">
                        <div class="links">
                            <a href="{% url 'user:password_reset' %}">Забыли пароль?</a>
                        </div>
                    </div>
                    <button class="button login__submit">
                        <span class="button__text">Войти</span>
                        <i class="button__icon fas fa-chevron-right"></i>
                    </button>
                </form>
            <button class="button login__submit login__register" onclick="window.location.href='{% url 'user:register' %}'">
                    <span class="button__text">Зарегистрироваться</span>
                </button>
            </div>
            <div class="screen__background">
                <span class="screen__background__shape screen__background__shape4"></span>
                <span class="screen__background__shape screen__background__shape3"></span>
                <span class="screen__background__shape screen__background__shape2"></span>
                <span class="screen__background__shape screen__background__shape1"></span>
            </div>
        </div>
    </div>
</body>
{% endblock %}

user/templates/registration_temp/password_change_done.html
{% extends 'base_user.html' %}
{% block title %}
Пароль Изменен
{% endblock %}
{% block content %}
<body>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-body text-center">
                    <h2 class="card-title">Пароль изменён</h2>
                    <p class="card-text">Ваш пароль был успешно изменён.</p>
                    <div class="btn-container">
                        <a href="{% url 'user:login' %}" class="btn custom-btn-login">
                            <i class="fas fa-sign-in-alt"></i> Войти
                        </a>
                        <a href="{% url 'games:main' %}" class="btn custom-btn-home">
                            <i class="fas fa-home"></i> На главную
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

user/templates/registration_temp/password_change_form.html
{% extends 'base_user.html' %}
{% block title %}
Изменить пароль
{% endblock %}
{% block content %}
<body>
<div class="container">
	<div class="screen">
		<div class="screen__content">
			<form class="login" method="post">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ next }}"/>
				<div class="form-error">{{ form.non_field_errors }}</div>
				{% for f in form %}
				<p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
				<div class="row-form-errors">{{ f.errors }}</div>
				{% endfor %}
				<button class="button login__submit">
					<span class="button__text">Сменить Пароль</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>
			</form>

		</div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div>
</body>
{% endblock %}

user/templates/registration_temp/password_reset_complete.html
{% extends 'base_user.html' %}
{% block title %}
Пароль Изменен
{% endblock %}
{% block content %}
<body>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-body text-center">
                    <h2 class="card-title">Пароль изменён</h2>
                    <p class="card-text">Ваш пароль был успешно изменён.</p>
                    <div class="btn-container">
                        <a href="{% url 'user:login' %}" class="btn custom-btn-login">
                            <i class="fas fa-sign-in-alt"></i> Войти
                        </a>
                        <a href="{% url 'games:main' %}" class="btn custom-btn-home">
                            <i class="fas fa-home"></i> На главную
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

user/templates/registration_temp/password_reset_confrim.html
{% extends 'base_user.html' %}
{% block title %}
Изменить пароль
{% endblock %}
{% block content %}
<body>
<div class="container">
	<div class="screen">
		<div class="screen__content">
			<form class="login" method="post">
				{% csrf_token %}
				<input type="hidden" name="next" value="{{ next }}"/>
				<div class="form-error">{{ form.non_field_errors }}</div>
				{% for f in form %}
				<p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
				<div class="row-form-errors">{{ f.errors }}</div>
				{% endfor %}
				<button class="button login__submit">
					<span class="button__text">Сменить Пароль</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>
			</form>

		</div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div>
</body>
{% endblock %}

user/templates/registration_temp/password_reset_done.html
{% extends 'base_user.html' %}
{% load i18n %}
{% block title %}

{% endblock %}
{% block content %}
<body>
<div class="container mt-4">
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-body text-center">
                    <p>{% translate 'We’ve emailed you instructions for setting your password, if an account exists with the email you entered. You should receive them shortly.' %}</p>

<p>{% translate 'If you don’t receive an email, please make sure you’ve entered the address you registered with, and check your spam folder.' %}</p>

                    <div class="btn-container">
                        <a href="{% url 'user:login' %}" class="btn custom-btn-login">
                            <i class="fas fa-sign-in-alt"></i> Войти
                        </a>
                        <a href="{% url 'games:main' %}" class="btn custom-btn-home">
                            <i class="fas fa-home"></i> На главную
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</body>
{% endblock %}

user/templates/registration_temp/password_reset_email.html
{% load i18n %}{% autoescape off %}
{% blocktranslate %}You're receiving this email because you requested a password reset for your user account at {{ site_name }}.{% endblocktranslate %}

{% translate "Please go to the following page and choose a new password:" %}
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'user:password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
{% translate 'Your username, in case you’ve forgotten:' %} {{ user.get_username }}

{% translate "Thanks for using our site!" %}

{% blocktranslate %}The {{ site_name }} team{% endblocktranslate %}

{% endautoescape %}

user/templates/registration_temp/password_reset_form.html
{% extends 'base_user.html' %}
{% block title %}
Восстановление пароля
{% endblock %}
{% block content %}
<body>
<div class="container">
	<div class="screen">
		<div class="screen__content">
			<form class="login" method="post">
				{% csrf_token %}
				<div class="form-error">{{ form.non_field_errors }}</div>
				{% for f in form %}
				<p><label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>{{ f }}</p>
				<div class="row-form-errors">{{ f.errors }}</div>
				{% endfor %}
				<button class="button login__submit">
					<span class="button__text">Сменить Пароль</span>
					<i class="button__icon fas fa-chevron-right"></i>
				</button>
			</form>

		</div>
		<div class="screen__background">
			<span class="screen__background__shape screen__background__shape4"></span>
			<span class="screen__background__shape screen__background__shape3"></span>
			<span class="screen__background__shape screen__background__shape2"></span>
			<span class="screen__background__shape screen__background__shape1"></span>
		</div>
	</div>
</div>
</body>
{% endblock %}

user/templates/registration_temp/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <title>Регистрация</title>
    <link href="{% static 'css/register.css' %}" rel="stylesheet">
  </head>
  <body>
    <!-- Body of Form starts -->
    <div class="container">
        <div class="screen">
            <div class="screen__content">
                <form class="login" method="post">
                    {% csrf_token %}
                    <input type="hidden" name="next" value="{{ next }}"/>
                    <div class="form-error">{{ form.non_field_errors }}</div>
                    {% for f in form %}
                    <div class="login__field">
                        <label class="form-label" for="{{ f.id_for_label }}">{{ f.label }}</label>
                        {{ f }}
                        <div class="form-error">{{ f.errors }}</div>
                    </div>
                    {% endfor %}
                    <!---Submit Button------>
                    <button class="button login__submit login__register">
                    <span class="button__text">Зарегистрироваться</span>
                    </button>
                    <!---Submit Button----->
                </form>
            </div>
            <div class="screen__background">
                <span class="screen__background__shape screen__background__shape4"></span>
                <span class="screen__background__shape screen__background__shape3"></span>
                <span class="screen__background__shape screen__background__shape2"></span>
                <span class="screen__background__shape screen__background__shape1"></span>
            </div>
        </div>
    </div>
    <!--Body of Form ends--->
  </body>
</html>